from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    CategoryListCreateAPIView,
    CertificateIssueAPIView,
    CertificateListAPIView,
    CertificateVerifyAPIView,
    CourseDetailAPIView,
    CourseListAPIView,
    EnrollAPIView,
    EnrollmentListAPIView,
    LessonDetailAPIView,
    LessonListCreateAPIView,
    LessonProgressAPIView,
    ModuleDetailAPIView,
    ModuleListCreateAPIView,
    PaymentListCreateAPIView,
    ProfileAPIView,
    ProgressListCreateAPIView,
    QuestionDetailAPIView,
    QuestionListCreateAPIView,
    QuizDetailAPIView,
    QuizListCreateAPIView,
    RegisterAPIView,
    ReviewListCreateAPIView,
)

urlpatterns = [
    path('auth/register/', RegisterAPIView.as_view(), name='api_register'),
    path('auth/me/', ProfileAPIView.as_view(), name='api_profile'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('categories/', CategoryListCreateAPIView.as_view(), name='api_categories'),
    path('courses/', CourseListAPIView.as_view(), name='api_courses'),
    path('courses/<int:pk>/', CourseDetailAPIView.as_view(), name='api_course_detail'),
    path('courses/<int:course_id>/enroll/', EnrollAPIView.as_view(), name='api_enroll'),
    path('modules/', ModuleListCreateAPIView.as_view(), name='api_modules'),
    path('modules/<int:pk>/', ModuleDetailAPIView.as_view(), name='api_module_detail'),
    path('lessons/', LessonListCreateAPIView.as_view(), name='api_lessons'),
    path('lessons/<int:pk>/', LessonDetailAPIView.as_view(), name='api_lesson_detail'),
    path('lessons/<int:lesson_id>/progress/', LessonProgressAPIView.as_view(), name='api_lesson_progress'),
    path('quizzes/', QuizListCreateAPIView.as_view(), name='api_quizzes'),
    path('quizzes/<int:pk>/', QuizDetailAPIView.as_view(), name='api_quiz_detail'),
    path('questions/', QuestionListCreateAPIView.as_view(), name='api_questions'),
    path('questions/<int:pk>/', QuestionDetailAPIView.as_view(), name='api_question_detail'),
    path('enrollments/', EnrollmentListAPIView.as_view(), name='api_enrollments'),
    path('progress/', ProgressListCreateAPIView.as_view(), name='api_progress'),
    path('certificates/', CertificateListAPIView.as_view(), name='api_certificates'),
    path('certificates/issue/<int:enrollment_id>/', CertificateIssueAPIView.as_view(), name='api_issue_certificate'),
    path('certificates/verify/<str:certificate_id>/', CertificateVerifyAPIView.as_view(), name='api_verify_certificate'),
    path('payments/', PaymentListCreateAPIView.as_view(), name='api_payments'),
    path('reviews/', ReviewListCreateAPIView.as_view(), name='api_reviews'),
]
